src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Blameable\Traits\BlameableEntity;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=BookingRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    use TimestampableEntity;
    use BlameableEntity;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity=Ad::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Warning the start Date bad format")
     * @Assert\GreaterThan("today", message="Start date must be minimum today")
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Date(message="Warning the end Date bad format")
     * @Assert\GreaterThan(propertyPath="startDate", message="The end date must be more start date")
     */
    private $endDate;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\PrePersist()
     *
     * @return void
     */
    public function prePersist()
    {
        if (empty($this->amount)) {
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    public function isBookableDates()
    {
        $notAvailableDays = $this->ad->getNotAvailableDays();
        $bookingDay = $this->getDays();

        $formatDay = function ($day) {
            return $day->format('Y-m-d');
        };

        $days = array_map($formatDay, $bookingDay);

        $notAvailable = array_map($formatDay, $notAvailableDays);

        foreach ($days as $day) {
            if (array_search($day, $notAvailable) !== false) {
                return false;
            }
        }

        return true;
    }

    /**
     * Recover array of all days who correspond at the booking
     *
     * @return array
     * @throws \Exception
     */
    public function getDays()
    {
        $result = range(
            $this->startDate->getTimestamp(),
            $this->endDate->getTimestamp(),
            24 * 60 * 60
        );

        $days = array_map(function ($dayTimestamp) {
            return new \DateTime(date('Y-m-d', $dayTimestamp));
        }, $result);

        return $days;
    }

    public function getDuration()
    {
        $diff = $this->endDate->diff($this->startDate);
        return $diff->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?Users
    {
        return $this->booker;
    }

    public function setBooker(?Users $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UsersRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"email"},
 *     message="This email is already used."
 * )
 */
class Users implements UserInterface
{
    use TimestampableEntity;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(name="id", type="integer")
     */
    private $id;

    /**
     * @ORM\Column(name="first_name", type="string", length=255)
     * @Assert\NotBlank(message="This field is missing.")
     */
    private $firstName;

    /**
     * @ORM\Column(name="last_name", type="string", length=255)
     * @Assert\NotBlank(message="This field is missing.")
     */
    private $lastName;

    /**
     * @ORM\Column(name="email", type="string", length=255)
     * @Assert\Email(message="The fields {{ fields }} were not expected.")
     */
    private $email;

    /**
     * @ORM\Column(name="picture", type="string", length=255, nullable=true)
     * @Assert\Url(message="This field is not valid")
     */
    private $picture;

    /**
     * @ORM\Column(name="password", type="string", length=255)
     */
    private $password;

    /**
     * @Assert\EqualTo(propertyPath="password", message="This fields not equal at field password")
     */
    public $passwordConfirm;

    /**
     * @ORM\Column(name="introduction", type="string", length=255)
     * @Assert\Length(min="10", minMessage="The introduction must be minimum 10 charcaters")
     */
    private $introduction;

    /**
     * @ORM\Column(name="description", type="text")
     * @Assert\Length(min="100", minMessage="The description must be minimum 100 charcaters")
     */
    private $description;

    /**
     * @ORM\Column(name="slug", type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(name="salt", type="string")
     */
    private $salt;

    /**
     * @ORM\OneToMany(targetEntity=Ad::class, mappedBy="author")
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function initialSlug()
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName. ' '. $this->lastName);
        }
    }

    public function getFullName()
    {
        return "{$this->firstName} {$this->lastName}";
    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->contains($ad)) {
            $this->ads->removeElement($ad);
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    public function getRoles()
    {
        $roles = $this->userRoles->map(function ($role) {
            return $role->getTitle();
        })->toArray();
        $roles[] = 'ROLE_USER';

        return $roles;
    }

    public function setSalt($salt)
    {
        $this->salt = $salt;
    }

    public function getSalt()
    {
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function eraseCredentials()
    {
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }
}

src/Controller/BookingController.php
<?php
/**
 * Created by PhpStorm
 * User: shadowluffy
 * Date: 9/27/20
 * Time: 5:14 PM
 */

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Form\BookingCreateType;
use App\Manager\BookingManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class BookingController
 * @package App\Controller
 *
 * @Route("/book", name="book_")
 *
 * @author CONTE Alexandre <pro.alexandre.conte@gmail.com>
 */
class BookingController extends AbstractController
{
    protected $bookingManager;

    public function __construct(
        BookingManager $bookingManager
    )
    {
        $this->bookingManager = $bookingManager;
    }

    /**
     * @Route("/{slug}/create", name="create")
     *
     * @IsGranted("ROLE_USER")
     * @param Ad $ad
     * @param Request $request
     *
     * @return Response
     */
    public function createBooking(Ad $ad, Request $request)
    {
        $booking = $this->bookingManager->createBooking();
        $form = $this->createForm(BookingCreateType::class, $booking);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $booking->setBooker($this->getUser())
                ->setAd($ad)
            ;
            // If date not available
            if (!$booking->isBookableDates()) {
                $this->addFlash(
                    'warning',
                    "This dates is already take"
                );
            } else {
                $this->bookingManager->save($booking);

                return $this->redirectToRoute('book_show', [
                    'id' => $booking->getId(),
                    'withAlert' => true
                ]);
            }
        }

        return $this->render('booking/create.html.twig', [
            'ad' => $ad,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/{id}/show", name="show")
     *
     * @param Booking $booking
     *
     * @return Response
     */
    public function showBooking(Booking $booking)
    {
        return $this->render('booking/show.html.twig', [
            'booking' => $booking
        ]);
    }
}

templates/booking/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create Book{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
{% endblock %}

{% block body %}
    <div class="container">
        <h2>Create book for announcement : {{ ad.title }}</h2>

        <p>You are about to book the property of <strong>{{ ad.author.fullName }}</strong></p>

        {{ form_start(form) }}
        <div class="alert alert-light">
            <h2>What are the dates you like ?</h2>
            <div class="row">
                <div class="col">
                    {{ form_row(form.startDate) }}
                </div>
                <div class="col">
                    {{ form_row(form.endDate) }}
                </div>
            </div>

            <h4>Amount of travel : <span id="amount">...</span>&euro;</h4>
            <span id="days">0</span> nights at {{ ad.price }} &euro;

            <h3>Write comment here :</h3>
            {{ form_row(form.comment) }}

            <button type="submit" class="btn btn-success">Book</button>

            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    <script
            src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js">
    </script>

    <script>
        $(document).ready(function () {
            $('#booking_create_startDate, #booking_create_endDate').datepicker({
                format: 'dd/mm/yyyy',
                datesDisabled: [
                    {% for day in ad.notAvailableDays %}
                    "{{ day.format('d/m/Y') }}",
                    {% endfor %}
                ],
                startDate: new Date()
            });
            $('#booking_create_startDate, #booking_create_endDate').on('change', calculateAmount);
        })

        function calculateAmount() {
            const endDate = new Date($('#booking_create_endDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));
            const startDate = new Date($('#booking_create_startDate').val().replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1'));

            if (startDate && endDate && startDate < endDate) {
                const DAY_TIME = 24 * 60 * 60 * 1000;
                const interval = endDate.getTime() - startDate.getTime();
                const days = interval / DAY_TIME;
                const amount = days * {{ ad.price }};

                $('#days').text(days)
                $('#amount').text(amount.toLocaleString('fr-Fr'))
            }


        }
    </script>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Booking n°{{ booking.id }}{% endblock %}

{% block body %}
    {% set ad = booking.ad %}
    {% set author = ad.author %}

    <div class="container">
        <h2>Your booking n°{{ booking.id }}</h2>
        {% if app.request.query.get('withAlert') %}
            <div class="alert alert-success">
                <h4 class="alert-heading">Congratulation !</h4>
                <p>
                    Your Booking near
                    <strong>
                        <a href="{{ path('user_profile', {'slug': author.slug}) }}">{{ author.fullName }}</a>
                    </strong>
                    for the announcement
                    <strong>
                        <a href="{{ path('ad_show', {'slug': ad.slug}) }}">{{ ad.title }}</a>
                    </strong>
                    has been taken into account !
                </p>
            </div>
        {% endif %}
        <div class="row">
            <div class="col">
                <div class="alert alert-light">
                    <h3>Details</h3>
                    <dl class="row">
                        <dt class="col-md-4">Number</dt>
                        <dd class="col-md-8">{{ booking.id }}</dd>
                        <dt class="col-md-4">Start Date</dt>
                        <dd class="col-md-8">{{ booking.startDate | date('d/m/Y') }}</dd>
                        <dt class="col-md-4">End Date</dt>
                        <dd class="col-md-8">{{ booking.endDate | date('d/m/Y') }}</dd>
                        <dt class="col-md-4">Number of Nights</dt>
                        <dd class="col-md-8">{{ booking.duration }}</dd>
                        <dt class="col-md-4">Amount Total</dt>
                        <dd class="col-md-8">{{ booking.amount }} &euro;</dd>
                        <dt class="col-md-4">Comment</dt>
                        <dd class="col-md-8">{{ booking.comment }}</dd>
                    </dl>

                    <hr>
                    
                    <h2 class="alert-heading">Our host</h2>
                    <div class="row">
                        <div class="col-3">
                            <img src="{{ author.picture }}" class="avatar avatar-medium" alt="Avatar of {{ author.fullName }}">
                        </div>
                        <div class="col-9">
                            <h4>
                                <a href="{{ path('user_profile', {'slug': author.slug}) }}">{{ author.fullName }}</a>
                            </h4>

                            <span class="badge badge-primary">{{ author.ads | length }} announcements</span>
                        </div>
                    </div>
                    {{ author.description | raw }}

                    <a href="{{ path('user_profile', {'slug': author.slug}) }}" class="btn btn-primary">See more on {{ author.firstName }}</a>
                </div>
            </div>
            <div class="col">
                <div class="alert alert-light">
                    <h2 class="alert-heading">Your hostname</h2>

                    <h4>
                        <a href="{{ path('ad_show', {'slug': ad.slug}) }}">{{ ad.title }}</a>
                    </h4>

                    <img src="{{ ad.coverImage }}" alt="Picture of {{ ad.title }}" class="img-fluid">

                    {{ ad.content | raw }}

                    <a href="{{ path('ad_show', {'slug': ad.slug}) }}" class="btn btn-primary">See more</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}